#!/usr/bin/env bash
# Configure your Nginx server so that "/redirect_me" is redirecting to another page.

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index.html
new_string="server_name\ _;\n\trewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "s|server_name\ _;|$new_string|" /etc/nginx/sites-available/default
sudo service nginx restart
