#!/usr/bin/env bash
# Clon of first server
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World" | sudo tee /var/www/html/index.html

new_string="server_name\ _;\n\trewrite ^/redirect_me/$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "s|server_name\ _;|$new_string|" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/error.html
newlines="\\\terror_page 404 /error.html;\n\tlocation = /error.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "27i $newlines" /etc/nginx/sites-available/default

new_new_string="server_name _;\n\tadd_header X-Served-By $HOSTNAME;"
sed -i "s|server_name\ _;|$new_new_string|" /etc/nginx/sites-available/default

sudo service nginx restart
sudo service nginx reload
