#!/usr/bin/env bash
# make your fix short and sweet
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
sudo kill 'cat /path/to/nginx.pid'