#!/usr/bin/env bash
# Write a Bash script that kills using SIGQUIT or SIGTERM.
sudo echo $$ > /var/run/myscript.pid
trap "echo 'I hate the kill command'; sudo rm  /var/run/myscript.pid; kill -9 $$" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "sudo rm  /var/run/myscript.pid; kill -9 $$" SIGQUIT

while true
do
	echo "To infinity and beyond"
	sleep 1
done
