#!/usr/bin/env bash
# This script is displaying "Best School" and diferents texts in lines 4 and 8
i=0
while [ $i -le 9 ]
do
((i++))
if [[ $i == 4 ]]
then
echo "bad luck"
continue
elif [[ $i == 8 ]]
then
echo "good luck"
continue
else
echo "Best School"
fi
done