#!/usr/bin/env bash
# This script is displaying text whit conditions and using case
i=0
while [ $i -le 19 ]
do
((i++))
case $i in "5")
echo "bad luck from China";;
"10")
echo "bad luck from Japan";;
"18")
echo "bad luck from Italy";;
esac
echo "$i"
done
