#!/usr/bin/env bash
# This script is displaying the time for 12 hours and 59 minutes
hour=0
min=1

while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    while [ $min -le 59 ]
    do
        echo "$min"
        if [[ $min == 59 ]]
            then
            min=1
            break
        fi
            ((min++))
    done
    ((hour++))
done
