#!/usr/bin/env bash
# Bash script that configures the container to fit the above requirements
sudo pkill -9 apache2
sudo chmod 644 /etc/nginx/nginx.conf
new_user="user nginx;";
sed -i "s|#user www-data;|user nginx;|" /etc/nginx/nginx.conf
sed -i "s|80 default_server|8080 default_server|" /etc/nginx/sites-available/default
sudo -u nginx service nginx start
