#!/usr/bin/env bash
# Bash script that configures the container to fit the above requirements
pkill -9 apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sed -i "s|#user\ www-data;|user nginx;|" /etc/nginx/nginx.conf
service nginx restart
